# Generated by Django 4.2.16 on 2024-10-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrapeVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'grape varieties',
            },
        ),
        migrations.AddField(
            model_name='wine',
            name='grape_varieties',
            field=models.ManyToManyField(related_name='wines', to='products.grapevariety'),
        ),
    ]
