# Generated by Django 4.2.16 on 2024-10-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_wine_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grapevariety',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
